import type { Metadata } from 'next'

import { text, title } from './fonts'
import './globals.css'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${title.variable} ${text.variable}`}>{children}</body>
    </html>
  )
}
